/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as FuturesRouteImport } from './routes/futures'
import { Route as EconomicCalendarRouteImport } from './routes/economic-calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuturesIndexRouteImport } from './routes/futures.index'
import { Route as FuturesMaRouteImport } from './routes/futures.ma'
import { Route as FuturesDomRouteImport } from './routes/futures.dom'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturesRoute = FuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicCalendarRoute = EconomicCalendarRouteImport.update({
  id: '/economic-calendar',
  path: '/economic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturesIndexRoute = FuturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FuturesRoute,
} as any)
const FuturesMaRoute = FuturesMaRouteImport.update({
  id: '/ma',
  path: '/ma',
  getParentRoute: () => FuturesRoute,
} as any)
const FuturesDomRoute = FuturesDomRouteImport.update({
  id: '/dom',
  path: '/dom',
  getParentRoute: () => FuturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/futures': typeof FuturesRouteWithChildren
  '/overview': typeof OverviewRoute
  '/futures/dom': typeof FuturesDomRoute
  '/futures/ma': typeof FuturesMaRoute
  '/futures/': typeof FuturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/overview': typeof OverviewRoute
  '/futures/dom': typeof FuturesDomRoute
  '/futures/ma': typeof FuturesMaRoute
  '/futures': typeof FuturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/futures': typeof FuturesRouteWithChildren
  '/overview': typeof OverviewRoute
  '/futures/dom': typeof FuturesDomRoute
  '/futures/ma': typeof FuturesMaRoute
  '/futures/': typeof FuturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/economic-calendar'
    | '/futures'
    | '/overview'
    | '/futures/dom'
    | '/futures/ma'
    | '/futures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/economic-calendar'
    | '/overview'
    | '/futures/dom'
    | '/futures/ma'
    | '/futures'
  id:
    | '__root__'
    | '/'
    | '/economic-calendar'
    | '/futures'
    | '/overview'
    | '/futures/dom'
    | '/futures/ma'
    | '/futures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EconomicCalendarRoute: typeof EconomicCalendarRoute
  FuturesRoute: typeof FuturesRouteWithChildren
  OverviewRoute: typeof OverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futures': {
      id: '/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof FuturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-calendar': {
      id: '/economic-calendar'
      path: '/economic-calendar'
      fullPath: '/economic-calendar'
      preLoaderRoute: typeof EconomicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futures/': {
      id: '/futures/'
      path: '/'
      fullPath: '/futures/'
      preLoaderRoute: typeof FuturesIndexRouteImport
      parentRoute: typeof FuturesRoute
    }
    '/futures/ma': {
      id: '/futures/ma'
      path: '/ma'
      fullPath: '/futures/ma'
      preLoaderRoute: typeof FuturesMaRouteImport
      parentRoute: typeof FuturesRoute
    }
    '/futures/dom': {
      id: '/futures/dom'
      path: '/dom'
      fullPath: '/futures/dom'
      preLoaderRoute: typeof FuturesDomRouteImport
      parentRoute: typeof FuturesRoute
    }
  }
}

interface FuturesRouteChildren {
  FuturesDomRoute: typeof FuturesDomRoute
  FuturesMaRoute: typeof FuturesMaRoute
  FuturesIndexRoute: typeof FuturesIndexRoute
}

const FuturesRouteChildren: FuturesRouteChildren = {
  FuturesDomRoute: FuturesDomRoute,
  FuturesMaRoute: FuturesMaRoute,
  FuturesIndexRoute: FuturesIndexRoute,
}

const FuturesRouteWithChildren =
  FuturesRoute._addFileChildren(FuturesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EconomicCalendarRoute: EconomicCalendarRoute,
  FuturesRoute: FuturesRouteWithChildren,
  OverviewRoute: OverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
